import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { connectDatabase, type Database } from "@tracepbl/repositories";
import { createApp } from "../src/app.js";
import type { ApiConfig } from "../src/config.js";

const runId=crypto.randomUUID();
const databaseUrl=process.env.TRACEPBL_TEST_APP_DATABASE_URL; let database:Database; let app:ReturnType<typeof createApp>;
const config={host:"127.0.0.1",port:8787,allowedOrigin:"http://127.0.0.1:5173",databaseUrl:databaseUrl??"postgres://unused",sessionSecret:"s".repeat(43),mode:"ci",aiConfigured:false,urlFetchEnabled:false,priceProfileVersion:null,generationReservationCnyMicros:0} satisfies ApiConfig;
beforeAll(()=>{if(databaseUrl){database=connectDatabase(databaseUrl,2);app=createApp(database,config);}}); afterAll(async()=>{if(database)await database.end();});
const suite=databaseUrl?describe:describe.skip;
suite("local API against least-privilege app role",()=>{
  let cookie="";let taskId="";let etag="";
  it("bootstraps a host-only session without exposing workspace",async()=>{const response=await app.request("http://127.0.0.1:8787/api/v1/runtime");expect(response.status).toBe(200);cookie=response.headers.get("set-cookie")!.split(";",1)[0]!;expect(JSON.stringify(await response.json())).not.toContain("workspace");});
  it("creates, reads, and optimistically updates a scoped task",async()=>{const headers={Cookie:cookie,Origin:config.allowedOrigin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","Idempotency-Key":`api-integration-create-0001-${runId}`};const created=await app.request("http://127.0.0.1:8787/api/v1/tasks",{method:"POST",headers,body:JSON.stringify({title:"合成 API 任务"})});expect(created.status).toBe(201);const task=await created.json() as {id:string};taskId=task.id;etag=created.headers.get("etag")!;
    const context={stage:"高中",grade:"高一",textbook:"合成教材",lesson:"合成课次",lessonTypes:["新授"],minutes:45,inquiryDirection:"合成问题",priorKnowledge:null,learningNeeds:[],profileNote:null};const updated=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/context`,{method:"PUT",headers:{...headers,"If-Match":etag},body:JSON.stringify(context)});expect(updated.status).toBe(200);etag=updated.headers.get("etag")!;const stale=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/context`,{method:"PUT",headers:{...headers,"If-Match":'"task-lv-0"'},body:JSON.stringify(context)});expect(stale.status).toBe(412);expect(JSON.stringify(await stale.json())).not.toMatch(/workspace|sql|stack/i);});
  it("saves unchanged context again without duplicating immutable history",async()=>{const headers={Cookie:cookie,Origin:config.allowedOrigin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","If-Match":etag};const read=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/context`,{headers:{Cookie:cookie}});expect(read.status).toBe(200);const historyBefore=await database`select id,content_hash from core.task_revisions where task_id=${taskId} order by revision_no`;const response=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/context`,{method:"PUT",headers,body:JSON.stringify({stage:"高中",grade:"高一",textbook:"合成教材",lesson:"合成课次",lessonTypes:["新授"],minutes:45,inquiryDirection:"合成问题",priorKnowledge:null,learningNeeds:[],profileNote:null})});expect(response.status).toBe(200);etag=response.headers.get("etag")!;expect(etag).toBe('"task-lv-2"');const historyAfter=await database`select id,content_hash from core.task_revisions where task_id=${taskId} order by revision_no`;expect(historyAfter).toEqual(historyBefore);});
  it("queues and cancels a task-scoped material operation",async()=>{const write={Cookie:cookie,Origin:config.allowedOrigin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json"};const added=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/materials`,{method:"POST",headers:{...write,"Idempotency-Key":`api-integration-material-0001-${runId}`},body:JSON.stringify({kind:"text",name:"合成材料",text:"仅用于后端集成测试的合成正文。",rightsAttestation:"authorizedForCurrentTask",sensitiveInformationConfirmedAbsent:true})});expect(added.status).toBe(202);const result=await added.json() as {operation:{id:string}};const cancelled=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/operations/${result.operation.id}`,{method:"DELETE",headers:{...write,"Idempotency-Key":`api-integration-cancel-0001-${runId}`},body:"{}"});expect(cancelled.status).toBe(200);expect(await cancelled.json()).toMatchObject({status:"cancelled"});const controller=new AbortController();const events=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/events`,{headers:{Cookie:cookie,"Last-Event-ID":"0"},signal:controller.signal});expect(events.headers.get("content-type")).toContain("text/event-stream");const reader=events.body!.getReader();let received="";for(let count=0;count<10&&!received.includes("operation.");count++){const part=await reader.read();if(part.done)break;received+=new TextDecoder().decode(part.value);}controller.abort();await reader.cancel();expect(received).toContain("operation.");});
  it("copies private material identities and enqueues a deterministic audit with the app role",async()=>{const write={Cookie:cookie,Origin:config.allowedOrigin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json"};const copied=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/copies`,{method:"POST",headers:{...write,"Idempotency-Key":`api-integration-copy-0001-${runId}`},body:JSON.stringify({title:"合成 API 副本"})});expect(copied.status).toBe(201);const audit=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/audits`,{method:"POST",headers:{...write,"If-Match":etag,"Idempotency-Key":`api-integration-audit-0001-${runId}`},body:JSON.stringify({baseLockVersion:2})});expect(audit.status).toBe(202);expect(await audit.json()).toMatchObject({reused:false,operation:{kind:"audit",status:"queued"}});const disabledUrl=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/materials`,{method:"POST",headers:{...write,"Idempotency-Key":`api-integration-url-0001-${runId}`},body:JSON.stringify({kind:"url",name:"合成网址",url:"https://example.invalid/",rightsAttestation:"authorizedForCurrentTask",sensitiveInformationConfirmedAbsent:true})});expect(disabledUrl.status).toBe(503);});
  it("rejects malformed opaque cursors",async()=>{const response=await app.request("http://127.0.0.1:8787/api/v1/tasks?cursor=not-a-cursor",{headers:{Cookie:cookie}});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({code:"MALFORMED_REQUEST"});});
  it("rejects a cross-origin write before touching data",async()=>{const response=await app.request(`http://127.0.0.1:8787/api/v1/tasks/${taskId}/context`,{method:"PUT",headers:{Cookie:cookie,Origin:"http://evil.invalid","Sec-Fetch-Site":"cross-site","Content-Type":"application/json","If-Match":etag},body:"{}"});expect(response.status).toBe(400);});
});
