import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
const modulePath=process.env.TRACEPBL_PLAYWRIGHT_MODULE;
if(!modulePath)throw new Error("Set existing TRACEPBL_PLAYWRIGHT_MODULE; no installation");
const origin=process.env.TRACEPBL_BROWSER_ORIGIN??"http://127.0.0.1:52173";
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin))throw new Error("Loopback only");
const output=resolve(process.env.TRACEPBL_BROWSER_EVIDENCE??`.tracepbl/stage13/run-${Date.now()}`);
await mkdir(output,{recursive:true});
const {chromium}=await import(pathToFileURL(resolve(modulePath)).href);
const browser=await chromium.launch({headless:true,args:["--no-proxy-server"]});
const context=await browser.newContext();const page=await context.newPage();const errors=[],external=[],checks=[];
await context.route("**/*",route=>{if(new URL(route.request().url()).origin!==origin){external.push("blocked external request");return route.abort();}return route.continue();});
page.on("pageerror",error=>errors.push(error.message));
const api=async(path,method="GET",body,version,key=crypto.randomUUID(),client=context)=>client.request.fetch(`${origin}/api/v1${path}`,{method,headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","Idempotency-Key":key,...(version===undefined?{}:{"If-Match":`"task-lv-${version}"`})},...(body===undefined?{}:{data:body})});
const button=name=>page.getByRole("button",{name,exact:true});
let stranger;
try{
 assert.equal((await (await api("/runtime")).json()).ai.execution,"fake");
 assert.equal((await (await api("/tasks")).json()).items.length,0);
 await page.goto(origin);await button("进入史料工作台").click();await page.waitForURL("**/context");
 const id=page.url().split("/tasks/")[1].split("/")[0],base=`/tasks/${id}`;
 assert.equal((await (await api(`${base}/sources`)).json()).items.length,0);
 await page.locator('input[name="textbook"]').fill("合成就绪教材");await page.locator('input[name="lesson"]').fill("合成材料比较");await page.locator('select[name="grade"]').selectOption("七年级");await page.locator('input[name="minutes"]').fill("45");await page.locator('textarea[name="inquiryQuestion"]').fill("如何用合成材料形成有条件的解释？");
 await button("继续形成探究问题").click();await page.waitForURL("**/question");await button("模拟 AI · 生成整组问题").click();await page.getByText("待确认 · 已填入栏目，可直接编辑",{exact:false}).waitFor({timeout:45000});await button("确认问题并查找史料").click();await page.waitForURL("**/sources");
 const consent=page.locator(".local-material-consent input");assert.equal(await consent.nth(0).isChecked(),false);assert.equal(await consent.nth(1).isChecked(),false);
 const file={name:"合成首次输入.txt",mimeType:"text/plain",buffer:Buffer.from("合成测试文本：甲记录与乙记录存在差别，不是真实史料。","utf8")};
 await page.locator('input[type="file"]').setInputFiles(file);await page.getByRole("alert").filter({hasText:"请先确认"}).waitFor();assert.equal((await (await api(`${base}/sources`)).json()).items.length,0);
 await consent.nth(0).check();await consent.nth(1).check();await page.locator('input[type="file"]').setInputFiles([]);await page.locator('input[type="file"]').setInputFiles(file);await page.getByRole("alert").filter({hasText:"材料已加入"}).waitFor();
 let items=(await (await api(`${base}/sources`)).json()).items;assert.equal(items.length,1);assert.equal(items[0].contentText,file.buffer.toString());assert.equal(items[0].rightsState,"unknown");assert.equal(items[0].verificationState,"pending");checks.push("empty-first-use-and-explicit-consent");
 const input={kind:"text",name:"合成元数据",text:"合成文字不应保存正文",rightsAttestation:"unknown",sensitiveInformationConfirmedAbsent:true};
 const key=crypto.randomUUID();const first=await api(`${base}/materials`,"POST",input,undefined,key);assert.equal(first.status(),202);const saved=await first.json();assert.equal(saved.operation,null);
 // Discarded response / replay uses the identical command, not a second import.
 const replay=await api(`${base}/materials`,"POST",input,undefined,key);assert.equal(replay.status(),202);assert.deepEqual(await replay.json(),saved);
 assert.equal((await api(`${base}/materials`,"POST",{...input,name:"变更内容"},undefined,key)).status(),409);
 const before=(await (await api(`${base}/sources`)).json()).items.length;
 const batch=[{...input,kind:"url",name:"合成网址",url:"https://example.invalid/synthetic"},{...input,text:"合".repeat(50001)},{...input,sensitiveInformationConfirmedAbsent:false}];delete batch[0].text;
 const statuses=[];for(const row of batch)statuses.push((await api(`${base}/materials`,"POST",row)).status());assert.deepEqual(statuses,[202,422,422]);
 assert.equal((await (await api(`${base}/sources`)).json()).items.length,before+1);
 const retry=await api(`${base}/materials`,"POST",{...input,name:"合成纠正项",text:"合成修正文本"});assert.equal(retry.status(),202);
 items=(await (await api(`${base}/sources`)).json()).items;assert.equal(items.length,4);for(const item of items.slice(1)){assert.equal(item.contentText,null);assert.equal(item.rightsState,"restricted_metadata_only");}checks.push("same-key-replay-conflict-partial-failure-retry-metadata-only");
 stranger=await browser.newContext();
 const denied=await api(`${base}/sources`,"GET",undefined,undefined,undefined,stranger),missing=await api(`/tasks/${crypto.randomUUID()}/sources`,"GET",undefined,undefined,undefined,stranger);
 assert.equal(denied.status(),401);assert.equal(missing.status(),401);const a=await denied.json(),b=await missing.json();for(const field of ["code","title","detail","status"])assert.equal(a[field],b[field]);
 const other=(await (await api("/tasks","POST",{title:"合成隔离对照"})).json()).id;assert.equal((await (await api(`/tasks/${other}/sources`)).json()).items.length,0);
 const current=await (await api(base)).json();assert.equal((await api(`${base}/source-selection`,"PUT",{sourceVersionIds:[items[0].versionId]},current.lockVersion)).status(),200);
 assert.equal((await api(`${base}/source-selection`,"PUT",{sourceVersionIds:[]},current.lockVersion)).status(),412);
 assert.equal((await api(`/tasks/${other}/source-selection`,"PUT",{sourceVersionIds:[items[0].versionId]},0)).status(),404);
 const latest=await (await api(base)).json();assert.equal((await api(`${base}/exports`,"POST",{format:"pdf",fileName:"合成未核验材料"},latest.lockVersion)).status(),409);checks.push("unauthenticated-task-isolation-version-conflict-export-gate");
 await page.reload();await page.locator(".own-materials").waitFor();await page.getByRole("button",{name:"合成首次输入.txt",exact:false}).first().waitFor();await page.screenshot({path:resolve(output,"sources.png"),fullPage:true});
 const deletion=await api(base,"DELETE",{impactConfirmed:true},latest.lockVersion);assert.equal(deletion.status(),202);const window=await deletion.json();assert.equal((await api(`${base}/sources`)).status(),404);assert.equal((await api(`${base}/restorations`,"POST",{},window.lockVersion)).status(),200);assert.equal((await (await api(`${base}/sources`)).json()).items.length,4);checks.push("delete-hide-undo-retains-batch");
 assert.equal((await page.evaluate(()=>indexedDB.databases())).length,0);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const result={status:"passed",taskId:id,checks,batchStatuses:statuses,materials:4,externalRequests:0,pageErrors:0};await writeFile(resolve(output,"result.json"),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){await page.screenshot({path:resolve(output,"failure.png"),fullPage:true});throw error;}finally{if(stranger)await stranger.close();await context.close();await browser.close();}
