import assert from "node:assert/strict";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { mkdir, writeFile } from "node:fs/promises";
const modulePath=process.env.TRACEPBL_PLAYWRIGHT_MODULE;
if(!modulePath)throw new Error("Set an existing TRACEPBL_PLAYWRIGHT_MODULE.");
const {chromium}=await import(pathToFileURL(resolve(modulePath)).href);
const origin=process.env.TRACEPBL_BROWSER_ORIGIN ?? "http://127.0.0.1:25173";
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin))throw new Error("Use loopback only.");
const browser=await chromium.launch({headless:true,args:["--no-proxy-server"]});
const context=await browser.newContext();const page=await context.newPage();
const api=async(path,method="GET",body,version)=>{
 const response=await context.request.fetch(`${origin}/api/v1${path}`,{method,headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","Idempotency-Key":crypto.randomUUID(),...(version===undefined?{}:{"If-Match":`"task-lv-${version}"`})},...(body===undefined?{}:{data:body})});
 assert.ok(response.ok(),`${method} ${path}: ${response.status()}`);return response.json();
};
try{
 assert.equal((await api("/runtime")).ai.execution,"fake");
 const task=(await api("/tasks","POST",{title:"合成取消与恢复验证"})).id;const base=`/tasks/${task}`;
 const lesson={stage:"初中",grade:"七年级",textbook:"合成教材",lesson:"合成恢复练习",lessonTypes:[],minutes:45,inquiryDirection:null,priorKnowledge:null,learningNeeds:[],profileNote:null};
 await api(`${base}/context`,"PUT",lesson,0);
 await page.goto(`${origin}${base}/question`);
 const button=name=>page.getByRole("button",{name,exact:true});
 let release;let arrived;const gate=new Promise(r=>{release=r;});const read=new Promise(r=>{arrived=r;});
 const pattern=`**/api/v1${base}/proposals/*`;let cancelled;
 await page.route(pattern,async route=>{const response=await route.fetch();cancelled=await response.json();arrived();await gate;await route.fulfill({response});});
 await button("模拟 AI · 生成整组问题").click();
 await Promise.race([read,new Promise((_,reject)=>setTimeout(()=>reject(new Error("No proposal")),30000))]);
 await context.setOffline(true);await page.locator('[data-connection="reconnecting"]').waitFor();
 await context.setOffline(false);
 await button("取消生成").click();release();
 await page.getByText("已取消生成，栏目内容保留。",{exact:true}).waitFor();
 assert.equal(await page.getByText("待确认 · 已填入栏目，可直接编辑",{exact:false}).count(),0);
 assert.equal((await api(base)).lockVersion,1);
 await page.unroute(pattern);
 const rejected=await context.request.post(`${origin}/api/v1${base}/proposals/${cancelled.revisionId}/adoption`,{headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Idempotency-Key":crypto.randomUUID(),"If-Match":'"task-lv-1"'},data:{generatedRevisionId:cancelled.revisionId,sections:["questionSet"],baseLockVersion:1}});
 assert.equal(rejected.status(),409);
 await button("模拟 AI · 生成整组问题").click();await page.getByText("待确认 · 已填入栏目，可直接编辑",{exact:false}).waitFor({timeout:30000});
 page.on("dialog",dialog=>dialog.accept());await page.reload();
 await page.getByText("有一份尚未确认的生成结果。",{exact:false}).waitFor({timeout:20000});
 assert.equal((await api(base)).lockVersion,1);
 await button("填入生成结果，替换此栏目").click();
 await page.getByText("待确认 · 已填入栏目，可直接编辑",{exact:false}).waitFor();
 const before=await page.locator('.question-form').innerText();
 await api(`${base}/context`,"PUT",{...lesson,minutes:40},1);
 await button("确认问题并查找史料").click();
 await page.getByText("内容已在另一窗口修改。",{exact:false}).waitFor({timeout:15000});
 assert.ok(page.url().endsWith('/question'));assert.equal((await api(base)).lockVersion,2);
 assert.equal(await page.locator('.question-form').innerText(),before);
 const output=resolve('.tracepbl/stage11-inline-recovery-verification');await mkdir(output,{recursive:true});
 const result={status:"passed",offlineRestored:true,cancelDoesNotFill:true,cancelledAdoptionRejected:true,reloadOffersUnconfirmedResult:true,staleConfirmationPreservesDraft:true};
 await writeFile(resolve(output,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await context.close();await browser.close();}
