import assert from "node:assert/strict";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
const modulePath = process.env.TRACEPBL_PLAYWRIGHT_MODULE;
if (!modulePath) throw new Error("Set an existing TRACEPBL_PLAYWRIGHT_MODULE.");
const engines = await import(pathToFileURL(resolve(modulePath)).href);
const engineName = process.env.TRACEPBL_BROWSER_ENGINE ?? "chromium";
if (!["chromium", "firefox", "webkit"].includes(engineName)) throw new Error("Unsupported test browser");
const browser = await engines[engineName].launch({ headless: true, ...(engineName === "chromium" ? { args: ["--no-proxy-server"] } : {}) });
const context = await browser.newContext();
const origin = process.env.TRACEPBL_BROWSER_ORIGIN ?? "http://127.0.0.1:15173";
if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)) throw new Error("Use loopback only.");
const api = async (path, method = "GET", body, version) => {
  const response = await context.request.fetch(`${origin}/api/v1${path}`, { method, headers: { Origin: origin, "Sec-Fetch-Site": "same-origin", "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID(), ...(version === undefined ? {} : { "If-Match": `"task-lv-${version}"` }) }, ...(body === undefined ? {} : { data: body }) });
  assert.ok(response.ok(), `${method} ${path}: ${response.status()}`); return response.json();
};
try {
  assert.equal((await api("/runtime")).ai.execution, "fake");
  const task = (await api("/tasks", "POST", { title: "合成栏目原位验证" })).id;
  const base = `/tasks/${task}`;
  const put = (section, body, version) => api(`${base}/${section}`, "PUT", body, version);
  await put("context", {stage:"初中",grade:"七年级",textbook:"合成教材",lesson:"合成栏目原位验证",lessonTypes:[],minutes:45,inquiryDirection:null,priorKnowledge:null,learningNeeds:[],profileNote:null}, 0);
  await put("question-set", {centralQuestion:"合成材料如何支持有条件的解释？",focus:"single",subQuestions:[],confirmed:true}, 1);
  const sources = (await api(`${base}/sources`)).items.filter(item => item.title.match(/^合成材料 [1-6]（非真实史料）$/)).map(item => item.versionId);
  assert.equal(sources.length, 6);
  await put("source-selection", {sourceVersionIds:sources}, 2);
  await put("evidence-map", {claims:[{text:"合成材料如何支持解释？",gapAccepted:false,relations:[{sourceVersionId:sources[0],kind:"supports",reason:"合成练习依据",citations:[{sourceVersionId:sources[0],chunkId:null,quotedText:null}]}]}]}, 3);
  await put("lesson-design", {activities:[{title:"合成证据活动",activityMinutes:40,transitionMinutes:0,studentAction:"比较并引用",evidenceProduct:"解释表格",difficulty:"证据边界",scaffold:"标明出处",sourceVersionIds:sources}]}, 4);
  await put("rubric", {items:[{title:"合成引用评价",activityOrdinals:[0],levels:[{key:"support",label:"需要支持",description:"提示下引用"},{key:"expected",label:"达到要求",description:"准确引用"},{key:"strong",label:"表现充分",description:"引用并限定结论"}]}]}, 5);
  const {mkdir,writeFile}=await import('node:fs/promises');
  const output=resolve(process.env.TRACEPBL_BROWSER_EVIDENCE ?? '.tracepbl/stage11-inline-ai-verification'); await mkdir(output,{recursive:true});
  const page=await context.newPage(); const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  const button=name=>page.getByRole('button',{name,exact:true});
  const generated=()=>page.getByText('待确认 · 已填入栏目，可直接编辑',{exact:false}).waitFor({timeout:45000});
  const generate=async label=>{await button(`模拟 AI · ${label}`).click();await generated();await button(`模拟 AI · ${label}`).waitFor();};
  await page.goto(`${origin}${base}/question`);
  await button('修改中心问题').click();
  const central=page.locator('textarea[name="centralQuestion"]'); const outcome=page.locator('textarea[name="evidenceOutcome"]');
  await central.fill('教师原先填写的问题？'); await outcome.fill('手工设置的课堂交付');
  await generate('生成中心问题');
  assert.notEqual(await central.inputValue(),'教师原先填写的问题？');
  assert.equal(await outcome.inputValue(),'手工设置的课堂交付');
  assert.equal((await api(base)).lockVersion,6);
  await outcome.fill('生成后修改的课堂交付');
  await button('撤销本次生成').click();
  assert.equal(await central.inputValue(),'教师原先填写的问题？');
  assert.equal(await outcome.inputValue(),'生成后修改的课堂交付');
  let release; let captured; const gate=new Promise(resolve=>{release=resolve;}); const arrived=new Promise(resolve=>{captured=resolve;});
  let originalProposal;
  const pattern=`**/api/v1${base}/proposals/*`;
  await page.route(pattern,async route=>{const response=await route.fetch(); originalProposal=await response.json();captured();await gate;await route.fulfill({response});});
  await button('模拟 AI · 生成中心问题').click();
  await Promise.race([arrived,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Proposal read did not arrive')),30000))]).catch(async error=>{console.error(await page.locator('.inline-ai-status').innerText());throw error;});
  await central.fill('生成期间的新输入？'); release();
  await button('填入生成结果，替换此栏目').waitFor({timeout:15000});
  assert.equal(await central.inputValue(),'生成期间的新输入？');
  await button('填入生成结果，替换此栏目').click(); await generated();
  await page.unroute(pattern);
  await central.fill('教师最终编辑的问题？');
  await button('完成修改中心问题').click();
  let failOnce=true; const keys=[];
  await page.route(`**/api/v1${base}/proposals/*/adoption`,async route=>{
    keys.push(route.request().headers()['idempotency-key']);
    assert.equal(route.request().postDataJSON().reviewedContent.centralQuestion,'教师最终编辑的问题？');
    if(failOnce){failOnce=false;const response=await route.fetch({headers:{...route.request().headers(),Origin:origin,'Sec-Fetch-Site':'same-origin'}});assert.equal(response.status(),200);return route.abort('failed');}
    return route.continue();
  });
  await button('确认问题并查找史料').click();
  await page.getByText('连接中断，尚不能确定保存结果。',{exact:false}).waitFor();
  assert.ok(page.url().endsWith('/question'));
  await button('确认问题并查找史料').click(); await page.waitForURL('**/sources');
  await page.unroute(`**/api/v1${base}/proposals/*/adoption`);
  assert.equal(keys[0],keys[1]); assert.equal((await api(base)).lockVersion,7);
  assert.equal((await api(`${base}/question-set`)).centralQuestion,'教师最终编辑的问题？');
  assert.deepEqual((await api(`${base}/proposals/${originalProposal.revisionId}`)).snapshot,originalProposal.snapshot);
  await page.goto(`${origin}${base}/evidence-map`);
  await generate('生成问题 1 的证据关系');
  await page.getByText('核对原文与来源',{exact:true}).first().click();
  await page.getByText('未附原文短引，请确认关系理由；模拟建议不代表证据已成立。',{exact:true}).first().waitFor();
  const reason=page.getByRole('textbox',{name:'关系理由（可修改）',exact:true}).first();
  await reason.fill('教师核对后修改的证据理由');
  assert.equal((await api(base)).lockVersion,7);
  await button('确认证据并设计活动').click();await page.waitForURL('**/lesson');
  assert.equal((await api(`${base}/evidence-map`)).claims[0].relations[0].reason,'教师核对后修改的证据理由');
  await generate('生成整课活动');
  const activity=page.locator('.activity-card').nth(1);
  await activity.getByRole('button',{name:'修改',exact:true}).click();
  await activity.locator('.activity-title-input').fill('教师活动二');
  await button('模拟 AI · 生成整课活动').click();
  await page.getByText('请先保存卡片内正在编辑的内容，再生成；不会覆盖未完成的修改。',{exact:true}).waitFor();
  assert.equal(await activity.locator('.activity-title-input').inputValue(),'教师活动二');
  await activity.getByRole('button',{name:'保存修改',exact:true}).click();
  const other=await page.locator('.activity-card').first().innerText();
  await generate('替换活动 2');
  await page.getByText('已填入替换活动 2',{exact:false}).waitFor();
  assert.equal(await page.locator('.activity-card').first().innerText(),other);
  assert.notEqual(await activity.locator('h2').innerText(),'教师活动二');
  await activity.getByRole('button',{name:'撤销本次生成',exact:true}).click();
  assert.equal(await activity.locator('h2').innerText(),'教师活动二');
  const layouts=[];
  const capture=async route=>{for(const width of [1774,390,320]){await page.setViewportSize({width,height:1114});const scroll=await page.evaluate(()=>document.documentElement.scrollWidth);assert.ok(scroll<=width,`${route} overflow at ${width}`);await page.screenshot({path:resolve(output,`${route}-${width}.png`),fullPage:true});layouts.push({route,width,scroll});}};
  await capture('lesson');
  await button('确认活动并设计量规').click();await page.waitForURL('**/rubric');
  await generate('生成整套量规');
  assert.equal(await page.locator('.rubric-row').count(),3); const firstDimension=await page.locator('.rubric-row').first().innerText();
  await generate('替换评价维度 2');
  await page.getByText('已填入替换评价维度 2',{exact:false}).waitFor();
  assert.equal(await page.locator('.rubric-row').first().innerText(),firstDimension);
  await capture('rubric');
  await button('确认量规并设计检查').click();await page.waitForURL('**/audit');
  for(const route of ['question','evidence-map']){await page.goto(`${origin}${base}/${route}`);await page.locator('.inline-ai-status').waitFor();await page.locator('main h1').waitFor();await capture(route);}
  assert.deepEqual(errors,[]);
  const result={status:'passed',fieldFill:true,undoPreservesOtherEdits:true,lateResultProtected:true,editedConfirmationAtomic:true,lostResponseSameKey:true,generatedHistoryPreserved:true,singleActivityReplacement:true,singleRubricReplacement:true,layouts,taskPath:base};
  await writeFile(resolve(output,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
} finally {await context.close();await browser.close();}
