import type { LocalTaskData } from "./local-task-data";
import type { TeachingContextDraft } from "./teaching-context";
import type { QuestionWorkspaceDraft } from "./question-workspace";
import type { SourceDiscoveryDraft, SourceRecord } from "./source-discovery";
import type { EvidenceMapDraft, RelationKind } from "./evidence-map";
import { createLessonDesignDraft, type LessonDesignDraft } from "./lesson-design";
import { createRubricDraft, type RubricDraft } from "./rubric-design";
import { createAuditDraft, type AuditDraft, type AuditCategory, type AuditSeverity } from "./design-audit";
import { createFinalReviewDraft } from "./final-review";

export const relationNames: Record<string, RelationKind> = { background: "背景条件", supports: "支持原因", turning_point: "关键转折", consequence: "后续影响", challenges_or_limits: "质疑或限制" };
export const relationKeys = Object.fromEntries(Object.entries(relationNames).map(([key, value]) => [value, key]));
export function localSources(data: LocalTaskData): SourceRecord[] {
  return data.sources.map(source => ({ id: source.versionId, title: source.title, nature: source.sourceType, role: "教师选择", institution: source.creatorOrInstitution, period: source.periodLabel ?? "未提供", locator: source.locator, url: source.url ?? "", excerpt: source.contentText ?? "当前仅提供元数据，正文不可用。", contextNote: source.contextNote ?? "未提供语境说明。", meaning: source.meaningNote ?? "尚无解读。", interpretation: source.interpretationNote ?? "尚无系统分析，需教师复核。", limitation: source.limitationNote ?? "适用边界尚待教师确认。", rights: source.rightsBasis, usable: ["verified", "conditional"].includes(source.verificationState) && ["verified_reusable", "restricted_metadata_only"].includes(source.rightsState), statusNote: source.rightsState === "restricted_metadata_only" ? "仅可使用元数据；正文不输出" : source.verificationState === "verified" && source.rightsState === "verified_reusable" ? "来源与权利已登记核验" : source.verificationState === "conditional" && source.rightsState === "verified_reusable" ? "有条件可用；请核对使用边界" : "核验或权利尚未满足，暂不可选用", recommended: false, questionIds: [] }));
}
export function localViewModel(data: LocalTaskData) {
  const context: TeachingContextDraft = data.context ? { ...data.context, minutes: String(data.context.minutes), inquiryQuestion: data.context.inquiryDirection ?? "", priorKnowledge: data.context.priorKnowledge ?? "", profileNote: data.context.profileNote ?? "" } : { stage: "", grade: "", textbook: "", lesson: "", lessonTypes: [], minutes: "", inquiryQuestion: "", priorKnowledge: "", learningNeeds: [], profileNote: "" };
  const question: QuestionWorkspaceDraft = { contextSnapshot: context, originalInput: context.inquiryQuestion, inputType: data.question?.inputType ?? "", typeReason: "教师当前问题", focus: data.question?.subQuestions.length ? "whole-lesson" : "single", centralQuestion: data.question?.centralQuestion ?? "", subQuestions: data.question?.subQuestions ?? [], evidenceOutcome: data.question?.evidenceOutcome ?? "", scopeBoundary: data.question?.scopeBoundary ?? "", confirmed: Boolean(data.question?.confirmed && data.task.reviewStates.questionSet === "ready") };
  const selected = data.sources.filter(source => source.selected).map(source => source.versionId);
  const source: SourceDiscoveryDraft = { fixtureVersion: 2, selectedIds: selected, batch: 0, needs: [], customNeed: "", ownMaterials: [] };
  const evidence: EvidenceMapDraft = { fixtureVersion: 2, questionSnapshot: question.centralQuestion, sourceSnapshot: selected, confirmed: data.evidence.claims.length > 0 && data.task.reviewStates.evidenceMap === "ready", claims: data.evidence.claims.map((claim, index) => ({ id: `QUESTION-${index + 1}`, text: claim.text, gapAccepted: claim.gapAccepted })), relations: data.evidence.claims.flatMap((claim, index) => claim.relations.map((relation, ordinal) => ({ id: `REL-${index}-${ordinal}`, claimId: `QUESTION-${index + 1}`, sourceId: relation.sourceVersionId, kind: relationNames[relation.kind], reason: relation.reason, citations: relation.citations, status: data.task.reviewStates.evidenceMap === "ready" ? "ready" as const : "needs-review" as const }))) };
  const lesson: LessonDesignDraft = { ...createLessonDesignDraft(question.centralQuestion, selected, evidence.relations), activities: data.lesson.activities.map((activity, index) => ({ ...activity, id: `ACT-${index + 1}`, minutes: activity.activityMinutes, sourceIds: activity.sourceVersionIds, teacherEdited: true, status: data.task.reviewStates.lessonDesign === "ready" ? "ready" : "needs-review" })), confirmed: data.lesson.activities.length > 0 && data.task.reviewStates.lessonDesign === "ready" };
  const rubric: RubricDraft = { ...createRubricDraft(lesson.activities), dimensions: data.rubric.items.map((item, index) => ({ id: `RUBRIC-${index}`, title: item.title, activityIds: item.activityOrdinals.map(ordinal => `ACT-${ordinal + 1}`), levels: item.levels, teacherEdited: true, status: data.task.reviewStates.rubric === "ready" ? "ready" : "needs-review" })), confirmed: data.rubric.items.length > 0 && data.task.reviewStates.rubric === "ready" };
  const auditInput = { question: question.centralQuestion, selectedSourceIds: selected, evidence, lesson, rubric };
  const currentAudit = data.audit?.status === "succeeded" && (data.audit.inputLockVersion === data.task.lockVersion || (data.task.workflowState === "approved" && data.audit.inputLockVersion + 1 === data.task.lockVersion));
  const severity: Record<string, AuditSeverity> = { blocking: "blocker", teacher_confirmation: "confirmation", suggestion: "suggestion", unknown: "unknown" };
  const category: Record<string, AuditCategory> = { evidence: "证据充分性", citation: "证据充分性", rights: "来源完整性", feasibility: "课堂可行性", alignment: "活动—评价一致性", completeness: "数据与范围" };
  const findings: AuditDraft["findings"] = currentAudit ? data.audit!.findings.filter(finding => finding.severity !== "pass").map(finding => ({ id: finding.id, severity: severity[finding.severity] ?? "unknown", category: category[finding.category] ?? "数据与范围", stage: (["rights"].includes(finding.category) || finding.subjectKind === "source_version" ? "史料" : ["evidence", "citation"].includes(finding.category) ? "论证" : finding.category === "feasibility" ? "活动" : finding.category === "alignment" ? "量规" : "问题"), title: finding.title, objectLabel: finding.title, basis: finding.basis, impact: finding.impact, recommendation: finding.recommendation ?? undefined, teacherReason: finding.teacherReason ?? "", resolution: finding.resolutionState === "accepted" || finding.resolutionState === "resolved" ? "accepted" : "pending" })) : [{ id: "SERVER-AUDIT-REQUIRED", severity: "unknown", category: "数据与范围", stage: "问题", title: "需要服务器设计检查", objectLabel: "当前任务修订", basis: "尚无与当前修订一致的成功检查。", impact: "不能签发教学包。", teacherReason: "", resolution: "pending" }];
  const audit: AuditDraft = { ...createAuditDraft(auditInput), findings, passedChecks: currentAudit && data.audit!.summary?.pass === true ? [{ id: data.audit!.id, category: "数据与范围", label: "服务器当前修订检查通过" }] : [], staleCategories: !currentAudit && data.audit && data.audit.inputLockVersion !== data.task.lockVersion ? ["数据与范围"] : [], completed: Boolean(currentAudit && !findings.some(finding => ["blocker", "unknown"].includes(finding.severity) || (finding.severity === "confirmation" && finding.resolution === "pending"))) };
  const finalInput = { ...auditInput, audit };
  const review = { ...createFinalReviewDraft(finalInput), fileName: data.task.title, approved: data.task.workflowState === "approved", confirmedAt: data.task.workflowState === "approved" ? data.task.updatedAt : null };
  return { context, question, source, evidence, lesson, rubric, audit, review };
}
