import { randomUUID } from "node:crypto";
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import { streamSSE } from "hono/streaming";
import { bodyLimit } from "hono/body-limit";
import { AdoptionRequestSchema, AsyncOperationSchema, AuditOperationSchema, AuditRequestSchema, AuditViewSchema, ContractVersion, TaskDetailSchema, OperationListSchema, CopyTaskSchema, CreateTaskSchema, DecisionRequestSchema, DecisionResultSchema, DeletionWindowSchema, EvidenceMapSchema, ExportManifestSchema, ExportOperationSchema, ExportRequestSchema, GeneratedProposalSchema, IdempotencyKeySchema, JobEventSchema, LessonDesignSchema, MaterialInputSchema, MaterialResultSchema, OperationStatusSchema, ProblemSchema, ProposalRequestSchema, QuestionSetSchema, RubricSchema, RuntimeSchema, SourceListSchema, SourceSelectionSchema, TaskListSchema, TaskSchema, TeachingContextSchema, UuidSchema, parseTaskEtag, taskEtag } from "@tracepbl/contracts";
import { DomainError, containsSensitiveData, mapStoredJobStatus, type WorkspaceScope } from "@tracepbl/domain";
import { FIXTURE_VERSION } from "@tracepbl/fixtures";
import { AiJobRepository, ContentRepository, JobRepository, SourceRepository, TaskRepository, WorkflowRepository, type Database, type JobRow } from "@tracepbl/repositories";
import type { ApiConfig } from "./config.ts";
import { issueSession, readSession } from "./session.ts";

type Variables = { traceId: string; scope: WorkspaceScope };
const problemResponses = { 400: { description: "Malformed request", content: { "application/problem+json": { schema: ProblemSchema } } }, 401: { description: "Session required", content: { "application/problem+json": { schema: ProblemSchema } } }, 404: { description: "Not found", content: { "application/problem+json": { schema: ProblemSchema } } }, 409: { description: "Invalid state or idempotency conflict", content: { "application/problem+json": { schema: ProblemSchema } } }, 412: { description: "Version conflict", content: { "application/problem+json": { schema: ProblemSchema } } }, 413: { description: "Input too large", content: { "application/problem+json": { schema: ProblemSchema } } }, 415: { description: "Unsupported media type", content: { "application/problem+json": { schema: ProblemSchema } } }, 422: { description: "Validation failed", content: { "application/problem+json": { schema: ProblemSchema } } }, 428: { description: "Precondition required", content: { "application/problem+json": { schema: ProblemSchema } } }, 429: { description: "Budget or rate limit exceeded", content: { "application/problem+json": { schema: ProblemSchema } } }, 500: { description: "Internal error", content: { "application/problem+json": { schema: ProblemSchema } } }, 503: { description: "Optional capability unavailable", content: { "application/problem+json": { schema: ProblemSchema } } } } as const;

function problem(c: Parameters<Parameters<OpenAPIHono<{ Variables: Variables }>["onError"]>[0]>[1], status: number, code: string, detail: string) {
  const traceId = c.get("traceId") || randomUUID();
  const body = { type: `https://tracepbl.local/problems/${code.toLowerCase().replaceAll("_", "-")}`, title: code === "RESOURCE_NOT_FOUND" ? "未找到资源" : "请求未完成", status, code, detail, traceId };
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/problem+json", "X-Trace-Id": traceId } });
}
function taskView(task: Awaited<ReturnType<TaskRepository["get"]>>) { return { id: task.id, title: task.title, workflowState: task.workflowState, lockVersion: task.lockVersion, deletedAt: task.deletedAt?.toISOString() ?? null, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() }; }
function taskSummaryView(task: Awaited<ReturnType<TaskRepository["get"]>>) { return { id: task.id, title: task.title, workflowState: task.workflowState, lockVersion: task.lockVersion, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() }; }
function jobView(job: JobRow) {
  const mapped = mapStoredJobStatus(job.status); const kinds: Record<string, z.infer<typeof OperationStatusSchema>["kind"]> = { source_check: "sourceCheck", embedding: "embedding", model: "model", audit: "audit", export: "export", purge: "purge" };
  const href=typeof job.payload.generatedRevisionId==="string"?`/api/v1/tasks/${job.taskId}/proposals/${job.payload.generatedRevisionId}`:job.status==="succeeded"&&typeof job.payload.runId==="string"?`/api/v1/tasks/${job.taskId}/audits/${job.payload.runId}`:job.status==="succeeded"&&typeof job.payload.exportId==="string"?`/api/v1/tasks/${job.taskId}/exports/${job.payload.exportId}/manifest`:null;
  return { id: job.id, kind: kinds[job.jobKind] ?? "model", status: mapped.status, ...(job.waitState === "teacher" ? { phase: "waitingForTeacher" as const } : job.status === "running" ? { phase: "processing" as const } : {}), completedItems: job.progressCurrent, ...(job.progressTotal === null ? {} : { totalItems: job.progressTotal }), attempt: job.attempts, canCancel: ["queued", "running"].includes(job.status) && job.jobKind !== "purge", startedAt: job.startedAt?.toISOString() ?? null, updatedAt: job.updatedAt.toISOString(), ...(href?{result:{href}}:{}), ...("errorCode" in mapped ? { error: { code: mapped.errorCode, message: "输入已变化，请重新发起。" } } : job.errorCode ? { error: { code: job.errorCode, message: "运行未完成。" } } : {}) };
}
const TaskCursorSchema=z.object({updatedAt:z.iso.datetime({offset:true}),id:UuidSchema}).strict();
function decodeTaskCursor(value:string|undefined){if(!value)return undefined;try{return TaskCursorSchema.parse(JSON.parse(Buffer.from(value,"base64url").toString("utf8")));}catch{throw new DomainError("MALFORMED_REQUEST","分页游标无效。");}}

export function createApp(database: Database, config: ApiConfig) {
  const app = new OpenAPIHono<{ Variables: Variables }>({ defaultHook: (result, c) => result.success ? undefined : result.target === "header" && result.error.issues.some(issue => issue.path.includes("if-match")) ? problem(c, 428, "PRECONDITION_REQUIRED", "需要有效的 If-Match。") : problem(c, 422, "VALIDATION_FAILED", "请求字段不符合契约。") });
  const tasks = new TaskRepository(database); const jobs = new JobRepository(database); const content = new ContentRepository(database); const sources = new SourceRepository(database); const aiJobs = new AiJobRepository(database);const workflow=new WorkflowRepository(database);
  const sessionStreams = new Map<string, number>(); const taskStreams = new Map<string, number>();
  app.use("*", async (c, next) => { const traceId = c.req.header("X-Trace-Id"); c.set("traceId", UuidSchema.safeParse(traceId).success ? traceId! : randomUUID()); await next(); c.header("X-Trace-Id", c.get("traceId")); });
  app.use("*",async(c,next)=>{const host=c.req.header("Host")||new URL(c.req.url).host;if(![`127.0.0.1:${config.port}`,`localhost:${config.port}`].includes(host))return problem(c,400,"MALFORMED_REQUEST","请求主机无效。");return next();});
  app.use("/api/v1/*",bodyLimit({maxSize:262_144,onError:(c)=>problem(c,413,"INPUT_TOO_LARGE","请求体超过允许大小。")}));
  app.use("/api/v1/*", async (c, next) => {
    if (c.req.path === "/api/v1/runtime") return next();
    const scope = readSession(c, config.sessionSecret); if (!scope) return problem(c, 401, "SESSION_REQUIRED", "请先建立本地会话。");
    if (!["GET", "HEAD", "OPTIONS"].includes(c.req.method)) {
      if (c.req.header("Origin") !== config.allowedOrigin || !["same-origin", "same-site"].includes(c.req.header("Sec-Fetch-Site") ?? "")) return problem(c, 400, "MALFORMED_REQUEST", "请求来源无效。");
      if ((c.req.header("Content-Type") ?? "").split(";", 1)[0]?.trim().toLowerCase() !== "application/json") return problem(c, 415, "UNSUPPORTED_MEDIA_TYPE", "写请求必须使用 application/json。");
    }
    c.set("scope", scope); return next();
  });
  app.onError((error, c) => {
    if (error instanceof DomainError) { const status = error.code === "MALFORMED_REQUEST" ? 400 : error.code === "RESOURCE_NOT_FOUND" ? 404 : error.code === "VERSION_CONFLICT" ? 412 : error.code === "PRECONDITION_REQUIRED" ? 428 : error.code === "AI_NOT_CONFIGURED" || error.code === "PROVIDER_UNAVAILABLE" ? 503 : error.code === "BUDGET_EXCEEDED" ? 429 : error.code === "VALIDATION_FAILED" || error.code === "CITATION_GATE_FAILED" ? 422 : 409; return problem(c, status, error.code, error.message); }
    if (error.message === "IDEMPOTENCY_KEY_REUSED") return problem(c, 409, error.message, "该幂等键已用于不同请求。");
    if (error.message === "VERSION_CONFLICT") return problem(c, 412, error.message, "内容已在另一窗口发生变化，请重新加载。");
    if (error.message === "BUDGET_EXCEEDED") return problem(c, 429, error.message, "今日 AI 使用额度不足。");
    if (error.message === "INVALID_STATE") return problem(c, 409, error.message, "当前状态不允许该操作。");
    if (error.message === "PURGE_ALREADY_STARTED") return problem(c, 409, error.message, "撤销窗口已结束，或到期清理已经开始。");
    if (error.message === "CITATION_GATE_FAILED") return problem(c, 422, error.message, "引用未通过来源与正文校验。");
    console.error(JSON.stringify({ level: "error", event: "request.failed", traceId: c.get("traceId"), code: "INTERNAL_ERROR" })); return problem(c, 500, "INTERNAL_ERROR", "服务器未能完成请求。");
  });

  app.get("/health/live", (c) => c.json({ status: "live" }));
  app.get("/health/ready", async (c) => { const rows = await database<{schema_ready:boolean;checkpointer_ready:boolean;overdue:number}[]>`select exists(select 1 from ops.runtime_components where component='backend_schema' and version='0004') as schema_ready,exists(select 1 from ops.runtime_components where component='langgraph_checkpointer') as checkpointer_ready,(select count(*)::int from core.tasks where deleted_at is not null and purge_after<=now()) as overdue`; const ready=Boolean(rows[0]?.schema_ready&&rows[0]?.checkpointer_ready&&rows[0]?.overdue===0);return ready ? c.json({ status: "ready" }) : c.json({ status: "not_ready" }, 503); });

  const runtime = createRoute({ method: "get", path: "/api/v1/runtime", operationId: "getRuntime", responses: { 200: { description: "Runtime capabilities", content: { "application/json": { schema: RuntimeSchema } } }, 500: problemResponses[500] } });
  app.openapi(runtime, async (c) => { const workspaceId = await tasks.localWorkspaceId(); issueSession(c, workspaceId, config.sessionSecret); const body = RuntimeSchema.parse({ mode: config.mode, contractVersion: ContractVersion, fixtureVersion: FIXTURE_VERSION, ai: { execution: config.providerMode ?? (config.aiConfigured ? "real" : "disabled"), available: config.aiConfigured, provider: "zhipu", generationModel: "GLM-5.3-Flash", embeddingModel: "embedding-3", reason: config.aiConfigured ? null : "AI_NOT_CONFIGURED" }, limits: { generationInputTokens: 24000, generationOutputTokens: 4000, callsPerAction: 2, dailyGenerationCalls: 20, dailyGenerationTokens: 200000, dailyEmbeddingTokens: 200000, dailyCny: 2, deleteGraceHours: 24 } }); return c.json(body, 200); });

  const listTasks = createRoute({ method: "get", path: "/api/v1/tasks", operationId: "listTasks", request: { query: z.object({ limit: z.coerce.number().int().min(1).max(100).default(20),cursor:z.string().max(500).optional() }) }, responses: { 200: { description: "Tasks", content: { "application/json": { schema: TaskListSchema } } }, ...problemResponses } });
  app.openapi(listTasks, async (c) => { const query=c.req.valid("query");const before=decodeTaskCursor(query.cursor); const rows = await tasks.list(c.get("scope"), query.limit,before?{updatedAt:new Date(before.updatedAt),id:before.id}:undefined); const visible = rows.slice(0, query.limit); return c.json({ items: visible.map((task) => taskSummaryView({ ...task, purgeAfter: null })), nextCursor: rows.length > query.limit ? Buffer.from(JSON.stringify({ updatedAt: visible.at(-1)!.updatedAt.toISOString(), id: visible.at(-1)!.id })).toString("base64url") : null }, 200); });

  const createTask = createRoute({ method: "post", path: "/api/v1/tasks", operationId: "createTask", request: { headers: z.object({ "idempotency-key": IdempotencyKeySchema }), body: { content: { "application/json": { schema: CreateTaskSchema } } } }, responses: { 201: { description: "Task", content: { "application/json": { schema: TaskSchema } } }, ...problemResponses } });
  app.openapi(createTask, async (c) => { const task = await tasks.create(c.get("scope"), c.req.valid("json").title, c.req.valid("header")["idempotency-key"]); c.header("ETag", taskEtag(task.lockVersion)); return c.json(taskView({ ...task, purgeAfter: null }), 201); });

  const getTask = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}", operationId: "getTask", request: { params: z.object({ taskId: UuidSchema }) }, responses: { 200: { description: "Task", content: { "application/json": { schema: TaskDetailSchema } } }, ...problemResponses } });
  app.openapi(getTask, async (c) => { const task = await tasks.detail(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); return c.json(TaskDetailSchema.parse({ ...task, deletedAt: task.deletedAt?.toISOString() ?? null, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() }), 200); });
  const copyTask=createRoute({method:"post",path:"/api/v1/tasks/{taskId}/copies",operationId:"copyTask",request:{params:z.object({taskId:UuidSchema}),headers:z.object({"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:CopyTaskSchema}}}},responses:{201:{description:"Independent task copy",content:{"application/json":{schema:TaskSchema}}},...problemResponses}});
  app.openapi(copyTask,async(c)=>{const task=await tasks.copy(c.get("scope"),c.req.valid("param").taskId,c.req.valid("json").title,c.req.valid("header")["idempotency-key"]);c.header("ETag",taskEtag(task.lockVersion));return c.json(taskView({...task,purgeAfter:null}),201);});

  const getContext = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/context", operationId: "getTaskContext", request: { params: z.object({ taskId: UuidSchema }) }, responses: { 200: { description: "Context", content: { "application/json": { schema: TeachingContextSchema.nullable() } } }, ...problemResponses } });
  app.openapi(getContext, async (c) => { const task = await tasks.get(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); const row = await tasks.getContext(c.get("scope"), task.id); if (!row) return c.json(null, 200); const body = TeachingContextSchema.parse({ stage: row.stage === "junior" ? "初中" : "高中", grade: row.grade, textbook: row.textbook, lesson: row.lesson, lessonTypes: row.lesson_types, minutes: Number(row.minutes), inquiryDirection: row.inquiry_direction, priorKnowledge: row.prior_knowledge, learningNeeds: row.learning_needs, profileNote: row.profile_note }); return c.json(body, 200); });

  const putContext = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/context", operationId: "putTaskContext", request: { params: z.object({ taskId: UuidSchema }), headers: z.object({ "if-match": z.string() }), body: { content: { "application/json": { schema: TeachingContextSchema } } } }, responses: { 200: { description: "Task", content: { "application/json": { schema: TaskSchema } } }, ...problemResponses } });
  app.openapi(putContext, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const task = await tasks.putContext(c.get("scope"), c.req.valid("param").taskId, expected, c.req.valid("json")); c.header("ETag", taskEtag(task.lockVersion)); return c.json(taskView({ ...task, purgeAfter: null }), 200); });

  const resourceParams = z.object({ taskId: UuidSchema }); const writeHeaders = z.object({ "if-match": z.string() });
  const getQuestionSet = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/question-set", operationId: "getQuestionSet", request: { params: resourceParams }, responses: { 200: { description: "Question set", content: { "application/json": { schema: QuestionSetSchema.nullable() } } }, ...problemResponses } });
  app.openapi(getQuestionSet, async (c) => { const task = await tasks.get(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); return c.json(QuestionSetSchema.nullable().parse(await content.questionSet(c.get("scope"), task.id)), 200); });
  const putQuestionSet = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/question-set", operationId: "putQuestionSet", request: { params: resourceParams, headers: writeHeaders, body: { content: { "application/json": { schema: QuestionSetSchema } } } }, responses: { 200: { description: "Question set", content: { "application/json": { schema: QuestionSetSchema } } }, ...problemResponses } });
  app.openapi(putQuestionSet, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const input = c.req.valid("json"); await content.putQuestionSet(c.get("scope"), c.req.valid("param").taskId, expected, input); c.header("ETag", taskEtag(expected + 1)); return c.json(input, 200); });

  const getSources = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/sources", operationId: "getSources", request: { params: resourceParams }, responses: { 200: { description: "Visible sources", content: { "application/json": { schema: SourceListSchema } } }, ...problemResponses } });
  app.openapi(getSources, async (c) => { const rows = await sources.list(c.get("scope"), c.req.valid("param").taskId); return c.json(SourceListSchema.parse({ items: rows.map((row) => ({ periodLabel: row.period_label, contextNote: row.context_note, meaningNote: row.meaning_note, interpretationNote: row.interpretation_note, limitationNote: row.limitation_note, rightsBasis: row.rights_basis, id: row.id, versionId: row.version_id, title: row.title, kind: row.material_kind, url: row.canonical_url, creatorOrInstitution: row.creator_or_institution, sourceType: row.source_type, locator: row.locator, contentText: row.content_text, rightsState: row.rights_state, verificationState: row.verification_state, selected: row.selected, selectionOrder: row.selection_order === null ? null : Number(row.selection_order) })) }), 200); });
  const addMaterial = createRoute({ method: "post", path: "/api/v1/tasks/{taskId}/materials", operationId: "addMaterial", request: { params: resourceParams, headers: z.object({ "idempotency-key": IdempotencyKeySchema }), body: { content: { "application/json": { schema: MaterialInputSchema } } } }, responses: { 202: { description: "Material and optional operation", content: { "application/json": { schema: MaterialResultSchema } } }, ...problemResponses } });
  app.openapi(addMaterial, async (c) => { const input = c.req.valid("json"); const untrusted = input.kind === "text" ? input.text : `${input.name} ${input.url}`; if (containsSensitiveData(untrusted)) throw new DomainError("VALIDATION_FAILED", "请移除秘密、姓名、联系方式或其他敏感信息。"); if(input.kind==="url"&&input.rightsAttestation==="authorizedForCurrentTask"&&!config.urlFetchEnabled) throw new DomainError("PROVIDER_UNAVAILABLE","URL 抓取开关未开启；可改为粘贴已获授权的文本。"); const result = await sources.createMaterial(c.get("scope"), c.req.valid("param").taskId, input, c.req.valid("header")["idempotency-key"]); const operation = typeof result.operationId === "string" ? jobView(await jobs.get(c.get("scope"), c.req.valid("param").taskId, result.operationId)) : null; return c.json(MaterialResultSchema.parse({ sourceId: result.sourceId, versionId: result.versionId, operation }), 202); });
  const selectSources = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/source-selection", operationId: "putSourceSelection", request: { params: resourceParams, headers: writeHeaders, body: { content: { "application/json": { schema: SourceSelectionSchema } } } }, responses: { 200: { description: "Selected source versions", content: { "application/json": { schema: SourceSelectionSchema } } }, ...problemResponses } });
  app.openapi(selectSources, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const input=c.req.valid("json"); await sources.select(c.get("scope"),c.req.valid("param").taskId,expected,input.sourceVersionIds); c.header("ETag",taskEtag(expected+1)); return c.json(input,200); });

  const getEvidenceMap = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/evidence-map", operationId: "getEvidenceMap", request: { params: resourceParams }, responses: { 200: { description: "Evidence map", content: { "application/json": { schema: EvidenceMapSchema } } }, ...problemResponses } });
  app.openapi(getEvidenceMap, async (c) => { const task = await tasks.get(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); return c.json(EvidenceMapSchema.parse(await content.evidenceMap(c.get("scope"), task.id)), 200); });
  const putEvidenceMap = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/evidence-map", operationId: "putEvidenceMap", request: { params: resourceParams, headers: writeHeaders, body: { content: { "application/json": { schema: EvidenceMapSchema } } } }, responses: { 200: { description: "Evidence map", content: { "application/json": { schema: EvidenceMapSchema } } }, ...problemResponses } });
  app.openapi(putEvidenceMap, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const input = c.req.valid("json"); await content.putEvidenceMap(c.get("scope"), c.req.valid("param").taskId, expected, input); c.header("ETag", taskEtag(expected + 1)); return c.json(input, 200); });

  const getLesson = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/lesson-design", operationId: "getLessonDesign", request: { params: resourceParams }, responses: { 200: { description: "Lesson design", content: { "application/json": { schema: LessonDesignSchema } } }, ...problemResponses } });
  app.openapi(getLesson, async (c) => { const task = await tasks.get(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); return c.json(LessonDesignSchema.parse(await content.lessonDesign(c.get("scope"), task.id)), 200); });
  const putLesson = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/lesson-design", operationId: "putLessonDesign", request: { params: resourceParams, headers: writeHeaders, body: { content: { "application/json": { schema: LessonDesignSchema } } } }, responses: { 200: { description: "Lesson design", content: { "application/json": { schema: LessonDesignSchema } } }, ...problemResponses } });
  app.openapi(putLesson, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const input = c.req.valid("json"); await content.putLessonDesign(c.get("scope"), c.req.valid("param").taskId, expected, input); c.header("ETag", taskEtag(expected + 1)); return c.json(input, 200); });

  const getRubric = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/rubric", operationId: "getRubric", request: { params: resourceParams }, responses: { 200: { description: "Rubric", content: { "application/json": { schema: RubricSchema } } }, ...problemResponses } });
  app.openapi(getRubric, async (c) => { const task = await tasks.get(c.get("scope"), c.req.valid("param").taskId); c.header("ETag", taskEtag(task.lockVersion)); return c.json(RubricSchema.parse(await content.rubric(c.get("scope"), task.id)), 200); });
  const putRubric = createRoute({ method: "put", path: "/api/v1/tasks/{taskId}/rubric", operationId: "putRubric", request: { params: resourceParams, headers: writeHeaders, body: { content: { "application/json": { schema: RubricSchema } } } }, responses: { 200: { description: "Rubric", content: { "application/json": { schema: RubricSchema } } }, ...problemResponses } });
  app.openapi(putRubric, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const input = c.req.valid("json"); await content.putRubric(c.get("scope"), c.req.valid("param").taskId, expected, input); c.header("ETag", taskEtag(expected + 1)); return c.json(input, 200); });

  const createProposal = createRoute({ method: "post", path: "/api/v1/tasks/{taskId}/proposals", operationId: "createProposal", request: { params: resourceParams, headers: z.object({ "if-match": z.string(), "idempotency-key": IdempotencyKeySchema }), body: { content: { "application/json": { schema: ProposalRequestSchema } } } }, responses: { 202: { description: "Proposal operation", content: { "application/json": { schema: AsyncOperationSchema } } }, ...problemResponses, 429: { description: "Budget exceeded", content: { "application/problem+json": { schema: ProblemSchema } } }, 503: { description: "AI not configured", content: { "application/problem+json": { schema: ProblemSchema } } } } });
  app.openapi(createProposal, async (c) => { if (!config.aiConfigured || !config.priceProfileVersion) throw new DomainError("AI_NOT_CONFIGURED", "AI 未配置或价格档案未确认。"); const expected=parseTaskEtag(c.req.valid("header")["if-match"]); if(expected===null) throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。"); const input=c.req.valid("json"); if(input.baseLockVersion!==expected) throw new DomainError("VERSION_CONFLICT","请求版本不一致。"); const created=await aiJobs.enqueueProposal(c.get("scope"),c.req.valid("param").taskId,input,c.req.valid("header")["idempotency-key"],config.priceProfileVersion,config.generationReservationCnyMicros); return c.json({ operation: jobView(await jobs.get(c.get("scope"),c.req.valid("param").taskId,created.jobId)) },202); });
  const getProposal=createRoute({method:"get",path:"/api/v1/tasks/{taskId}/proposals/{revisionId}",operationId:"getProposal",request:{params:z.object({taskId:UuidSchema,revisionId:UuidSchema})},responses:{200:{description:"Validated generated proposal",content:{"application/json":{schema:GeneratedProposalSchema}}},...problemResponses}});
  app.openapi(getProposal,async(c)=>{const row=await aiJobs.proposal(c.get("scope"),c.req.valid("param").taskId,c.req.valid("param").revisionId);const purposes:Record<string,z.infer<typeof GeneratedProposalSchema>["purpose"]>={question_guidance:"questionGuidance",source_analysis:"sourceAnalysis",evidence_analysis:"evidenceAnalysis",lesson:"lesson",rubric:"rubric",audit:"audit"};return c.json(GeneratedProposalSchema.parse({revisionId:row.id,purpose:purposes[String(row.purpose)],baseLockVersion:Number(row.base_lock_version),status:"validated",snapshot:row.snapshot}),200);});
  const adoptProposal=createRoute({method:"post",path:"/api/v1/tasks/{taskId}/proposals/{revisionId}/adoption",operationId:"adoptProposal",request:{params:z.object({taskId:UuidSchema,revisionId:UuidSchema}),headers:z.object({"if-match":z.string(),"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:AdoptionRequestSchema}}}},responses:{200:{description:"Updated task after teacher adoption",content:{"application/json":{schema:TaskSchema}}},...problemResponses}});
  app.openapi(adoptProposal,async(c)=>{const expected=parseTaskEtag(c.req.valid("header")["if-match"]);if(expected===null)throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。");const input=c.req.valid("json");const params=c.req.valid("param");if(input.generatedRevisionId!==params.revisionId||input.baseLockVersion!==expected||input.sections.length!==1)throw new DomainError("INVALID_STATE","建议版本、任务版本或采用分项不一致。");const row=await aiJobs.proposal(c.get("scope"),params.taskId,params.revisionId);const stored=row.snapshot as {proposal?:unknown};const purpose=String(row.purpose);const definitions={question_guidance:{section:"questionSet" as const,schema:QuestionSetSchema},evidence_analysis:{section:"evidenceMap" as const,schema:EvidenceMapSchema},lesson:{section:"lessonDesign" as const,schema:LessonDesignSchema},rubric:{section:"rubric" as const,schema:RubricSchema}};const definition=definitions[purpose as keyof typeof definitions];if(!definition||input.sections[0]!==definition.section)throw new DomainError("INVALID_STATE","该建议不能采用到所选分项。");const parsed=definition.schema.safeParse(input.reviewedContent ?? stored.proposal);if(!parsed.success)throw new DomainError("VALIDATION_FAILED","建议结构不符合当前分项契约。");await workflow.adopt(c.get("scope"),params.taskId,params.revisionId,definition.section,parsed.data as unknown as Record<string,unknown>,expected,c.req.valid("header")["idempotency-key"]);const task=await tasks.get(c.get("scope"),params.taskId);c.header("ETag",taskEtag(task.lockVersion));return c.json(taskView(task),200);});

  const createAudit=createRoute({method:"post",path:"/api/v1/tasks/{taskId}/audits",operationId:"createAudit",request:{params:resourceParams,headers:z.object({"if-match":z.string(),"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:AuditRequestSchema}}}},responses:{202:{description:"Audit operation",content:{"application/json":{schema:AuditOperationSchema}}},...problemResponses}});
  app.openapi(createAudit,async(c)=>{const expected=parseTaskEtag(c.req.valid("header")["if-match"]);if(expected===null)throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。");const input=c.req.valid("json");if(input.baseLockVersion!==expected)throw new DomainError("VERSION_CONFLICT","请求版本不一致。");const result=await workflow.enqueueAudit(c.get("scope"),c.req.valid("param").taskId,input,c.req.valid("header")["idempotency-key"]);return c.json(AuditOperationSchema.parse({runId:result.runId,reused:result.reused,operation:jobView(await jobs.get(c.get("scope"),c.req.valid("param").taskId,result.jobId))}),202);});
  const getAudit=createRoute({method:"get",path:"/api/v1/tasks/{taskId}/audits/{runId}",operationId:"getAudit",request:{params:z.object({taskId:UuidSchema,runId:UuidSchema})},responses:{200:{description:"Audit and findings",content:{"application/json":{schema:AuditViewSchema}}},...problemResponses}});
  app.openapi(getAudit,async(c)=>{const row=await workflow.audit(c.get("scope"),c.req.valid("param").taskId,c.req.valid("param").runId);return c.json(AuditViewSchema.parse({id:row.id,inputLockVersion:Number(row.input_lock_version),status:row.status,summary:row.summary,createdAt:(row.created_at as Date).toISOString(),completedAt:row.completed_at?(row.completed_at as Date).toISOString():null,findings:(row.findings as Record<string,unknown>[]).map(item=>({id:item.id,severity:item.severity,category:item.category,title:item.title,basis:item.basis,impact:item.impact,recommendation:item.recommendation,subjectKind:item.subject_kind,subjectId:item.subject_id,teacherReason:item.teacher_reason,resolutionState:item.resolution_state}))}),200);});
  const decide=createRoute({method:"post",path:"/api/v1/tasks/{taskId}/decisions",operationId:"createDecision",request:{params:resourceParams,headers:z.object({"if-match":z.string(),"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:DecisionRequestSchema}}}},responses:{201:{description:"Teacher decision",content:{"application/json":{schema:DecisionResultSchema}}},...problemResponses}});
  app.openapi(decide,async(c)=>{const expected=parseTaskEtag(c.req.valid("header")["if-match"]);if(expected===null)throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。");const result=await workflow.decide(c.get("scope"),c.req.valid("param").taskId,c.req.valid("json"),expected,c.req.valid("header")["idempotency-key"]);c.header("ETag",taskEtag(Number(result.lockVersion)));return c.json(DecisionResultSchema.parse(result),201);});
  const createExport=createRoute({method:"post",path:"/api/v1/tasks/{taskId}/exports",operationId:"createExport",request:{params:resourceParams,headers:z.object({"if-match":z.string(),"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:ExportRequestSchema}}}},responses:{202:{description:"Export operation",content:{"application/json":{schema:ExportOperationSchema}}},...problemResponses}});
  app.openapi(createExport,async(c)=>{const expected=parseTaskEtag(c.req.valid("header")["if-match"]);if(expected===null)throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。");const result=await workflow.enqueueExport(c.get("scope"),c.req.valid("param").taskId,c.req.valid("json"),expected,c.req.valid("header")["idempotency-key"]);return c.json(ExportOperationSchema.parse({exportId:result.exportId,operation:jobView(await jobs.get(c.get("scope"),c.req.valid("param").taskId,result.jobId))}),202);});
  const getManifest=createRoute({method:"get",path:"/api/v1/tasks/{taskId}/exports/{exportId}/manifest",operationId:"getExportManifest",request:{params:z.object({taskId:UuidSchema,exportId:UuidSchema})},responses:{200:{description:"Immutable export manifest",content:{"application/json":{schema:ExportManifestSchema}}},...problemResponses}});
  app.openapi(getManifest,async(c)=>c.json(ExportManifestSchema.parse(await workflow.exportManifest(c.get("scope"),c.req.valid("param").taskId,c.req.valid("param").exportId)),200));

  const deleteTask = createRoute({ method: "delete", path: "/api/v1/tasks/{taskId}", operationId: "deleteTask", request: { params: z.object({ taskId: UuidSchema }), headers: z.object({ "if-match": z.string(), "idempotency-key": IdempotencyKeySchema }), body: { content: { "application/json": { schema: z.object({ impactConfirmed: z.literal(true) }).strict() } } } }, responses: { 202: { description: "Deletion window", content: { "application/json": { schema: DeletionWindowSchema } } }, ...problemResponses } });
  app.openapi(deleteTask, async (c) => { const expected = parseTaskEtag(c.req.valid("header")["if-match"]); if (expected === null) throw new DomainError("PRECONDITION_REQUIRED", "需要有效的 If-Match。"); const result = await tasks.softDelete(c.get("scope"), c.req.valid("param").taskId, expected, c.req.valid("header")["idempotency-key"]); return c.json(result, 202); });
  const restoreTask = createRoute({ method: "post", path: "/api/v1/tasks/{taskId}/restorations", operationId: "restoreTask", request: { params: z.object({taskId:UuidSchema}),headers:z.object({"if-match":z.string(),"idempotency-key":IdempotencyKeySchema}),body:{content:{"application/json":{schema:z.object({}).strict()}}}}, responses:{200:{description:"Restored task",content:{"application/json":{schema:TaskSchema}}},...problemResponses} });
  app.openapi(restoreTask,async(c)=>{const expected=parseTaskEtag(c.req.valid("header")["if-match"]);if(expected===null)throw new DomainError("PRECONDITION_REQUIRED","需要有效的 If-Match。");const task=await tasks.restore(c.get("scope"),c.req.valid("param").taskId,expected,c.req.valid("header")["idempotency-key"]);c.header("ETag",taskEtag(task.lockVersion));return c.json(taskView({...task,purgeAfter:null}),200);});

  const listOperations = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/operations", operationId: "listOperations", request: { params: resourceParams, query: z.object({ limit: z.coerce.number().int().min(1).max(100).default(20), cursor: z.string().max(500).optional() }) }, responses: { 200: { description: "Task operations", content: { "application/json": { schema: OperationListSchema } } }, ...problemResponses } });
  app.openapi(listOperations, async (c) => {
    const query = c.req.valid("query"); let before: string | undefined;
    if (query.cursor) { try { before = UuidSchema.parse(Buffer.from(query.cursor, "base64url").toString("utf8")); } catch { throw new DomainError("MALFORMED_REQUEST", "分页游标无效。"); } }
    const rows = await jobs.list(c.get("scope"), c.req.valid("param").taskId, query.limit, before); const visible = rows.slice(0, query.limit);
    return c.json(OperationListSchema.parse({ items: visible.map(jobView), nextCursor: rows.length > query.limit ? Buffer.from(visible.at(-1)!.id).toString("base64url") : null }), 200);
  });
  const getOperation = createRoute({ method: "get", path: "/api/v1/tasks/{taskId}/operations/{operationId}", operationId: "getOperation", request: { params: z.object({ taskId: UuidSchema, operationId: UuidSchema }) }, responses: { 200: { description: "Operation", content: { "application/json": { schema: OperationStatusSchema } } }, ...problemResponses } });
  app.openapi(getOperation, async (c) => c.json(jobView(await jobs.get(c.get("scope"), c.req.valid("param").taskId, c.req.valid("param").operationId)), 200));
  const cancelOperation = createRoute({ method: "delete", path: "/api/v1/tasks/{taskId}/operations/{operationId}", operationId: "cancelOperation", request: { params: z.object({ taskId: UuidSchema, operationId: UuidSchema }), headers: z.object({ "idempotency-key": IdempotencyKeySchema }), body: { content: { "application/json": { schema: z.object({}).strict() } } } }, responses: { 200: { description: "Cancellation state", content: { "application/json": { schema: OperationStatusSchema } } }, ...problemResponses } });
  app.openapi(cancelOperation, async (c) => c.json(jobView(await jobs.cancel(c.get("scope"),c.req.valid("param").taskId,c.req.valid("param").operationId,c.req.valid("header")["idempotency-key"])),200));

  const taskEvents=createRoute({method:"get",path:"/api/v1/tasks/{taskId}/events",operationId:"streamTaskEvents",request:{params:z.object({taskId:UuidSchema}),headers:z.object({"last-event-id":z.string().optional()})},responses:{200:{description:"Task-scoped SSE event replay and live updates",content:{"text/event-stream":{schema:z.string()}}},...problemResponses,429:{description:"Too many event streams",content:{"application/problem+json":{schema:ProblemSchema}}}}});
  app.openapi(taskEvents, async (c) => {
    const taskId=c.req.valid("param").taskId; const rawLast=c.req.valid("header")["last-event-id"]??"0"; if(!/^\d+$/.test(rawLast))return problem(c,400,"MALFORMED_REQUEST","Last-Event-ID 无效。");const last=Number(rawLast);if(!Number.isSafeInteger(last))return problem(c,400,"MALFORMED_REQUEST","Last-Event-ID 无效。");
    const scope=c.get("scope");await tasks.get(scope,taskId);const sessionKey=scope.sessionId;const taskKey=`${scope.workspaceId}:${taskId}`;if((sessionStreams.get(sessionKey)??0)>=3||(taskStreams.get(taskKey)??0)>=2)return problem(c,429,"RATE_LIMITED","事件连接过多，请稍后重试或使用状态查询。");sessionStreams.set(sessionKey,(sessionStreams.get(sessionKey)??0)+1);taskStreams.set(taskKey,(taskStreams.get(taskKey)??0)+1);
    return streamSSE(c,async(stream)=>{let released=false;const release=()=>{if(released)return;released=true;const sessionCount=(sessionStreams.get(sessionKey)??1)-1;const taskCount=(taskStreams.get(taskKey)??1)-1;if(sessionCount>0)sessionStreams.set(sessionKey,sessionCount);else sessionStreams.delete(sessionKey);if(taskCount>0)taskStreams.set(taskKey,taskCount);else taskStreams.delete(taskKey);};stream.onAbort(release);const abort=()=>stream.abort();c.req.raw.signal.addEventListener("abort",abort,{once:true});let cursor=last;let heartbeatAt=Date.now();try{await stream.write(": connected\n\n");if(cursor>0&&!(await jobs.eventExists(scope,taskId,cursor))){const reset=JobEventSchema.parse({id:String(cursor),schemaVersion:1,type:"stream.reset",occurredAt:new Date().toISOString()});await stream.writeSSE({id:reset.id,event:reset.type,retry:3000,data:JSON.stringify(reset)});cursor=0;}while(!stream.aborted){const events=await jobs.events(scope,taskId,cursor);for(const event of events){const payload=JobEventSchema.parse({id:String(event.id),schemaVersion:Number(event.schema_version),type:event.event_type,...(event.payload as object),occurredAt:(event.occurred_at as Date).toISOString()});await stream.writeSSE({id:payload.id,event:payload.type,retry:3000,data:JSON.stringify(payload)});cursor=Number(event.id);}if(Date.now()-heartbeatAt>=15_000){await stream.write(": heartbeat\n\n");heartbeatAt=Date.now();}await stream.sleep(2_000);}}finally{release();c.req.raw.signal.removeEventListener("abort",abort);}}); });

  app.doc31("/openapi.json", { openapi: "3.1.0", info: { title: "TracePBL Local API", version: ContractVersion }, servers: [{ url: `http://127.0.0.1:${config.port}` }] });
  return app;
}
